### ISSUE TITLE
Make auto-gen for bot classes

### ISSUE THREAD

**Issue by Burtorustum** [0207-Critical-Mass/0207-Relic-Recovery#5]
Based on a robots hardware and desires keybindings, generate neccesary boilerplate (basic functions, enums, teleop) to allow for easier creation of robot code in later years.

**Comment by Weznon** [comment]
Might want to make a new report for this.

Would be fairly complex.

**Comment by Weznon** [comment]
Stupid phone won't let me assign two people

**Comment by Weznon** [comment]
https://github.com/0207-Critical-Mass/Bot-Class-Creator

new repo for this - closing this issue
